jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Upgrade
          command: 'apt-get update'
      - run:
          name: Installing SUDO
          command: 'apt-get install -y sudo'
      - run:
          name: Installing Flex and Bison
          command: 'sudo apt-get install -y gcc g++ flex bison'
      - run:
          name: Installing CMAKE
          command: 'sudo apt-get install -y cmake'
      - run:
          name: Running Bison
          command: 'bison --defines=src/query/interpreter/parser.tab.h --output=src/query/interpreter/parser.tab.c src/query/interpreter/parser/parser.y'
      - run:
          name: Running Flex
          command: 'flex --outfile=src/query/interpreter/lex.yy.c src/query/interpreter/lexer/lang.l'